import Head from 'next/head'
import  Router  from 'next/router'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="flex flex-col items-center justify-center min-h-screen py-2">
          <main className="flex flex-col items-center justify-center flex-1 px-20 text-center">
            <h1 className="text-6xl font-bold">
              Welcome to{' '}
              <Link className="text-blue-600" href="wordle"> 
               Wordle
              </Link>
            </h1>
            <p className="mt-3 text-2xl">
              Get started by editing{' '}
              <code className="p-3 font-mono text-lg bg-gray-100 rounded-md">
                pages/index.js
              </code>
            </p>
            <div className="flex flex-wrap items-center justify-around max-w-4xl mt-6 sm:w-full">
              <button
                onClick={() => Router.push('/wordle')}
                className="p-6 mt-6 text-left border w-96 rounded-xl hover:text-blue-600 focus:text-blue-600"
              >
              
    
                <h3 className="text-2xl font-bold">Wordle &rarr;</h3>
                <p className="mt-4 text-xl">
                  lets play wordle
                </p>
              </button>
    </div>
    </main>
    </div>
          
    </>
  )
}
