import Head from 'next/head'
import  Router  from 'next/router'

export default function Home() {
  return (
    <>
      <Head>
      <meta http-equiv="Refresh" content="0; url='https://go.ahmetkok.dev/bio'" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Hello World
      </h1>
      <button onClick={() => Router.push('/wordle')}>Wordle</button>
      
    </>
  )
}
